sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - '5.6'
  - '7.0'
  - '7.1'

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: '5.6'
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
      composer global require "phpunit/phpunit ^6"
    elif [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then
      composer global require "phpunit/phpunit ^5"
    else
      composer global require "phpunit/phpunit ^7"
    fi
  - composer global require "squizlabs/php_codesniffer=*"
  - composer global require wp-coding-standards/wpcs
  - phpcs --config-set installed_paths $HOME/.config/composer/vendor/wp-coding-standards/wpcs

script:
  - phpcs --standard=phpcs.ruleset.xml $(find . -name '*.php')
  - phpunit
