version: "3.5"

services:
  wordpress:
    image: "wordpress:${WP_VERSION:-6.4}-php${PHP_VERSION:-7.4}-apache"
    environment:
      VIRTUAL_HOST: "${DOCKER_DEV_DOMAIN:-project.test}"
      WORDPRESS_DB_HOST: "mysql"
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_PASSWORD: ""
      WORDPRESS_DB_USER: "root"
    depends_on:
      - mysql
    networks:
      - back
    ports:
      - "80:80"
    volumes:
      - "wp:/var/www/html:rw"
      - "./workshop-butler:/var/www/html/wp-content/plugins/workshop-butler:ro"
  wp-cli:
    image: "wordpress:cli-php${PHP_VERSION:-7.4}"
    environment:
    - APACHE_RUN_USER="www-data"
    - APACHE_RUN_GROUP="www-data"
    depends_on:
    - "mysql"
    networks:
    - "back"
    volumes:
    - "wp:/var/www/html:rw"
    - "./workshop-butler:/var/www/html/wp-content/plugins/workshop-butler:ro"
  mysql:
    image: "mariadb:10.6"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: ""
    networks:
      - "back"

networks:
  back: {}

volumes:
  wp: {}
